### ISSUE TITLE
Lightweight prior line map

### ISSUE THREAD

**Issue by DoongLi** [ZHENGXi-git/TC-VIML#2]
Hi, nice work~ I have some questions for lightweight prior line map generation, it seem like there dont document about it.

**Comment by ZHENGXi-git** [comment]
Hi, the line map is listed at 'benchmark_publisher/config/V1_01_easy/line_3d.txt'. The method of line generation is shown in our paper.

**Comment by DoongLi** [comment]
Will this code open source?

**Comment by ZHENGXi-git** [comment]
The line detection method we used comes from others' paper, I remember the code is open sourced. I suggest you to review the original paper.

**Comment by DoongLi** [comment]
Thx a lot~ Have a great day!
